services:
  db_service:
    container_name: db_container
    env_file:
      - .env
    image: postgres:14.5
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask_service:
    container_name: flask_container
    env_file:
      - .env
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${FLASK_RUN_PORT}:5000"
    depends_on:
      db_service:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db_container
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true

volumes:
  db_data:
